CREATE SCHEMA translator;
ALTER SCHEMA translator OWNER TO postgres;
CREATE SEQUENCE public.usr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.usr_id_seq OWNER TO postgres;
CREATE SEQUENCE public.usr_id_usr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.usr_id_usr_seq OWNER TO postgres;
CREATE TABLE translator."Original_Texts" (
    id_orig_t integer NOT NULL,
    source_content character varying,
    cod_trad_resq integer,
    cod_typ_writing integer
);
ALTER TABLE translator."Original_Texts" OWNER TO postgres;
ALTER TABLE translator."Original_Texts" ALTER COLUMN id_orig_t ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Original_Texts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator."Shipping_History" (
    "id_shipp_H" integer NOT NULL,
    "date_Subm" timestamp with time zone,
    envoy boolean,
    cod_translation integer
);
ALTER TABLE translator."Shipping_History" OWNER TO postgres;
ALTER TABLE translator."Shipping_History" ALTER COLUMN "id_shipp_H" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Shipping_History_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator."Translation_Requests" (
    id_t_reque integer NOT NULL,
    date_request timestamp with time zone,
    state character varying,
    shipping_edium character varying,
    cod_usr bigint
);
ALTER TABLE translator."Translation_Requests" OWNER TO postgres;
ALTER TABLE translator."Translation_Requests" ALTER COLUMN id_t_reque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Translation_Requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator."Translations" (
    id_trans integer NOT NULL,
    transld_contn character varying,
    translation_date timestamp with time zone,
    cod_text_oring integer
);
ALTER TABLE translator."Translations" OWNER TO postgres;
ALTER TABLE translator."Translations" ALTER COLUMN id_trans ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Translations_id_trans_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator."Types_Writing" (
    id_typ_w integer NOT NULL,
    nombre character varying,
    description character varying
);
ALTER TABLE translator."Types_Writing" OWNER TO postgres;
ALTER TABLE translator."Types_Writing" ALTER COLUMN id_typ_w ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Types_Writing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator.usr (
    id_usr integer NOT NULL,
    name character varying,
    email character varying,
    registration_date timestamp with time zone,
    password character varying
);
ALTER TABLE translator.usr OWNER TO postgres;
ALTER TABLE translator.usr ALTER COLUMN id_usr ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME translator."Usr_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE translator.usr_admin (
    id_usr character varying NOT NULL,
    name character varying,
    email character varying,
    password character varying,
    cod_usr integer,
    cod_transl integer,
    "cod_transl_H" integer
);
ALTER TABLE translator.usr_admin OWNER TO postgres;
CREATE SEQUENCE translator.usr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE translator.usr_id_seq OWNER TO postgres;
CREATE SEQUENCE translator.usr_id_usr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE translator.usr_id_usr_seq OWNER TO postgres;
1	El papiro est en la habitacin del faran Tucancamon	1	1
2	Las toneladas de trigo las llevan rumbo al puerto para comercializar con extranjeros provenientes de Grecia y Babilonia	9	1
3	Las toneladas de trigo las llevan rumbo al puerto para comercializar con extranjeros provenientes de Grecia y Babilonia	10	1
4	Las toneladas de trigo las llevan rumbo al puerto para comercializar con extranjeros provenientes de Grecia y Babilonia	11	1
5	La relacin entre la gastronoma y el arte culinario se traduce en una fusin de sabores que nos deleitan.	12	1
6	La relacin entre la gastronoma y el arte culinario se traduce en una fusin de sabores que nos deleitan	13	1
7	La relacin entre la gastronoma y el arte culinario se traduce en una fusin de sabores que nos deleitan	14	1
8	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	15	1
9	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	16	2
10	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	17	2
11	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	18	2
12	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	19	2
13	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	20	2
14	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	21	2
15	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	22	2
16	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	23	2
17	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	24	2
18	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	25	2
19	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	26	2
20	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	27	2
21	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	28	2
22	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	29	2
23	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	30	2
24	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	31	2
25	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	32	2
26	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	33	2
27	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	34	2
28	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	35	2
29	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	36	2
30	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	37	2
31	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	38	2
32	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	39	2
33	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	40	2
34	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	41	2
35	El difcil que una persona comprenda algo cuando su salario depende de que no lo comprenda	42	2
36	jjjjjjj	43	2
37	es dificil que una persona comprenda algo cuando su salario depende de que no lo comprenda	44	2
38	Escrito est	45	2
39	escrito esta	46	2
40	"La libertad es el derecho a decirle a la gente lo que no quiere or".	47	2
41	"La libertad es el derecho a decirle a la gente lo que no quiere oir".	48	2
42	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	49	1
43	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	50	2
44	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	51	2
45	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	52	2
46	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	53	2
47	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	54	1
48	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	55	1
49	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	56	1
50	Si el lider dice de tal evento esto no ocurrio, pues no ocurrio. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	57	1
51	Si el lider dice de tal evento esto no ocurrio, pues no ocurrio. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	58	1
52	Si el lider dice de tal evento esto no ocurrio	59	1
53	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	60	1
54	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	61	1
55	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	62	1
56	Si el líder dice de tal evento esto no ocurrió, pues no ocurrió. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho más que las bombas.	63	1
57	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	64	1
58	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	65	1
59	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	66	1
60	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	67	1
61	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	68	1
62	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	69	1
63	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	70	1
64	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	71	1
65	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	72	1
66	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	73	1
67	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	74	1
68	Si el lder dice de tal evento esto no ocurri, pues no ocurri. Si dice que dos y dos son cinco, pues dos y dos son cinco. Esta perspectiva me preocupa mucho ms que las bombas.	75	1
69	Si el lider dice de tal evento esto no ocurrio las bombas	76	1
70	Si el lider dice de tal evento esto no ocurrio las bombas	77	1
71	Si el lider dice de tal evento esto no ocurrio las bombas	78	1
72	Si el lider dice de tal evento esto no ocurrio las bombas	79	1
73	Si el lider dice de tal evento esto no ocurrio las bombas	80	1
74	Si el lider dice de tal evento esto no ocurrio las bombas	81	1
75	Si el lider dice de tal evento esto no ocurrio las bombas	82	1
76	Si el lider dice de tal evento esto no ocurrio las bombas	83	1
77	Si el lider dice de tal evento esto no ocurrio las bombas	84	1
78	Si el lider dice de tal evento esto no ocurrio las bombas	85	1
79	Si el lider dice de tal evento esto no ocurrio las bombas	86	1
80	Si el lider dice de tal evento esto no ocurrio las bombas	87	1
81	Si el lder dice de tal evento esto no ocurrio las bombas	88	1
82	Si el lider dice de tal evento esto no ocurrio las bombas	89	1
83	Si el lider dice de tal evento esto no ocurrio	90	1
84	Si el lider dice de tal evento esto no ocurrio las bombas	91	1
85	Si el lider dice de tal evento esto no ocurrio las bombas	92	1
86	Si el lider dice de tal evento esto no ocurrio las bombas	93	1
87	Escrito esta	94	1
88	Capivara, capivara sabe mucho y no se asara	95	2
89	Nado como un pez	96	2
90	Soy como un jabali pero mas chiquito	97	2
91	traduccion	98	1
92	Escrito esta	99	1
1	2025-05-04 18:06:01-05	1	email	2
3	2025-05-14 13:03:20.821582-05	pendiente	web	1
4	2025-05-15 12:33:43.252329-05	pendiente	web	15
5	2025-05-15 22:17:05.180157-05	pendiente	web	15
6	2025-05-15 22:38:14.782433-05	pendiente	web	15
7	2025-05-16 18:29:12.306289-05	pendiente	web	15
8	2025-05-16 18:30:48.632517-05	pendiente	web	15
9	2025-05-16 18:32:01.009425-05	pendiente	web	15
10	2025-05-16 18:34:00.943126-05	pendiente	web	15
11	2025-05-16 18:35:04.342961-05	pendiente	web	17
12	2025-05-16 18:41:11.260301-05	pendiente	web	18
13	2025-05-16 18:41:31.166803-05	pendiente	web	18
14	2025-05-16 18:41:32.255344-05	pendiente	web	18
15	2025-05-18 00:22:22.168352-05	pendiente	web	17
16	2025-05-18 00:27:33.104881-05	pendiente	web	17
17	2025-05-18 00:27:56.741355-05	pendiente	web	17
18	2025-05-18 00:29:48.668078-05	pendiente	web	17
19	2025-05-18 00:30:06.288388-05	pendiente	web	17
20	2025-05-18 00:31:35.312052-05	pendiente	web	17
21	2025-05-18 00:37:33.70903-05	pendiente	web	17
22	2025-05-18 00:43:39.201832-05	pendiente	web	17
23	2025-05-18 00:45:35.711398-05	pendiente	web	17
24	2025-05-18 00:46:31.085119-05	pendiente	web	17
25	2025-05-18 00:53:38.632256-05	pendiente	web	17
26	2025-05-18 00:53:51.871741-05	pendiente	web	17
27	2025-05-18 01:00:43.54117-05	pendiente	web	17
28	2025-05-18 01:01:03.548684-05	pendiente	web	17
29	2025-05-18 01:03:56.245311-05	pendiente	web	17
30	2025-05-18 01:20:11.455404-05	pendiente	web	17
31	2025-05-18 01:20:27.476341-05	pendiente	web	17
32	2025-05-18 01:21:12.326649-05	pendiente	web	17
33	2025-05-18 01:22:03.494939-05	pendiente	web	18
34	2025-05-18 01:30:18.328406-05	pendiente	web	18
35	2025-05-18 01:30:51.239431-05	pendiente	web	18
36	2025-05-18 01:34:58.78798-05	pendiente	web	18
37	2025-05-18 01:35:08.289273-05	pendiente	web	18
38	2025-05-18 01:35:18.63667-05	pendiente	web	18
39	2025-05-18 01:35:20.347682-05	pendiente	web	18
40	2025-05-18 01:35:33.644895-05	pendiente	web	18
41	2025-05-18 01:38:57.670748-05	pendiente	web	18
42	2025-05-18 01:41:33.631529-05	pendiente	web	18
43	2025-05-18 01:43:54.420891-05	pendiente	web	18
44	2025-05-18 01:45:20.69309-05	pendiente	web	18
45	2025-05-18 01:57:23.204493-05	pendiente	web	18
46	2025-05-18 01:58:25.541476-05	pendiente	web	18
47	2025-05-18 02:08:36.398674-05	pendiente	web	17
48	2025-05-18 02:08:44.710257-05	pendiente	web	17
49	2025-05-18 12:39:38.988254-05	pendiente	web	17
50	2025-05-18 12:45:37.531308-05	pendiente	web	17
51	2025-05-18 12:46:52.380623-05	pendiente	web	17
52	2025-05-18 13:14:48.046329-05	pendiente	web	17
53	2025-05-18 13:20:11.827896-05	pendiente	web	17
54	2025-05-18 13:28:06.090625-05	pendiente	web	17
55	2025-05-18 14:01:05.103446-05	pendiente	web	17
56	2025-05-18 14:01:23.289174-05	pendiente	web	17
57	2025-05-18 14:02:03.864146-05	pendiente	web	17
58	2025-05-18 14:02:17.479471-05	pendiente	web	17
59	2025-05-18 14:02:27.321059-05	pendiente	web	17
60	2025-05-18 14:05:15.880219-05	pendiente	web	18
61	2025-05-18 14:05:27.321251-05	pendiente	web	18
62	2025-05-18 14:11:30.929066-05	pendiente	web	18
63	2025-05-18 14:11:42.104743-05	pendiente	web	18
64	2025-05-18 14:14:20.84344-05	pendiente	web	18
65	2025-05-18 15:00:20.086169-05	pendiente	web	18
66	2025-05-18 15:00:48.33129-05	pendiente	web	18
67	2025-05-18 15:01:10.85736-05	pendiente	web	18
68	2025-05-18 15:23:28.595759-05	pendiente	web	18
69	2025-05-18 15:23:37.170683-05	pendiente	web	18
70	2025-05-18 15:34:59.187165-05	pendiente	web	18
71	2025-05-18 15:41:36.332636-05	pendiente	web	18
72	2025-05-18 15:41:42.009321-05	pendiente	web	18
73	2025-05-18 18:14:58.641498-05	pendiente	web	18
74	2025-05-18 18:15:09.995151-05	pendiente	web	18
75	2025-05-18 18:15:59.743731-05	pendiente	web	18
76	2025-05-18 18:17:57.846517-05	pendiente	web	18
77	2025-05-18 18:18:22.451335-05	pendiente	web	18
78	2025-05-18 18:19:41.498761-05	pendiente	web	18
79	2025-05-18 18:19:53.648021-05	pendiente	web	18
80	2025-05-18 18:21:06.347361-05	pendiente	web	18
81	2025-05-18 18:21:08.272645-05	pendiente	web	18
82	2025-05-18 18:22:48.120825-05	pendiente	web	18
83	2025-05-18 18:23:48.382818-05	pendiente	web	18
84	2025-05-18 18:23:57.327286-05	pendiente	web	18
85	2025-05-18 18:24:54.196265-05	pendiente	web	18
86	2025-05-18 18:26:30.932489-05	pendiente	web	18
87	2025-05-18 18:27:06.804743-05	pendiente	web	18
88	2025-05-18 18:31:59.190534-05	pendiente	web	18
89	2025-05-18 18:40:40.825411-05	pendiente	web	18
90	2025-05-18 18:51:25.959879-05	pendiente	web	18
91	2025-05-18 19:09:36.553121-05	pendiente	web	18
92	2025-05-18 19:15:03.830551-05	pendiente	web	18
93	2025-05-18 19:15:34.9992-05	pendiente	web	18
94	2025-05-18 19:50:42.446921-05	pendiente	web	15
95	2025-05-18 20:25:02.653873-05	pendiente	web	15
96	2025-05-18 20:52:07.122879-05	pendiente	web	20
97	2025-05-21 21:05:55.412224-05	pendiente	web	21
98	2025-05-23 11:39:17.056299-05	pendiente	web	15
99	2025-05-23 14:33:55.210421-05	pendiente	web	15
1	143256734577555	2025-05-15 18:06:01-05	1
2	ainolibaB y aicerG ed setneinevorp sorejnartxe noc razilaicremoc arap otreup la obmur navell sal ogirt ed sadalenot saL	2025-05-16 18:35:04.347321-05	4
3	jjjjjjj	2025-05-18 01:43:54.425333-05	36
4	adnerpmoc ol on euq ed edneped oiralas us odnauc ogla adnerpmoc anosrep anu euq licifid se	2025-05-18 01:45:20.699239-05	37
5	atse otircse	2025-05-18 01:58:25.545628-05	39
6	."rio ereiuq on euq ol etneg al a elriced a ohcered le se datrebil aL"	2025-05-18 02:08:44.713611-05	41
7	oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 14:02:27.325438-05	52
8	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:17:57.852458-05	69
9	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:18:22.454852-05	70
10	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:19:41.503072-05	71
11	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:19:53.651061-05	72
12	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:21:06.354541-05	73
13	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:21:08.275781-05	74
14	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:22:48.124544-05	75
15	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:23:48.385758-05	76
16	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:23:57.331757-05	77
17	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:24:54.199105-05	78
18	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:26:30.937396-05	79
19	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:27:06.809948-05	80
20	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:40:40.828796-05	82
21	oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 18:51:25.964435-05	83
22	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 19:09:36.560009-05	84
23	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 19:15:03.836282-05	85
24	sabmob sal oirruco on otse otneve lat ed ecid redil le iS	2025-05-18 19:15:35.003738-05	86
25	atse otircsE	2025-05-18 19:50:42.454294-05	87
26	arasa es on y ohcum ebas aravipac ,aravipaC	2025-05-18 20:25:02.659116-05	88
27	zep nu omoc odaN	2025-05-18 20:52:07.126406-05	89
28	otiuqihc sam orep ilabaj nu omoc yoS	2025-05-21 21:05:55.426544-05	90
29	noiccudart	2025-05-23 11:39:17.063187-05	91
30	atse otircsE	2025-05-23 14:33:55.214415-05	92
1	Runas vikinga	Las runas vikingas: cada una describe una letra caracter del alfabeto vikingo
2	Lenguaje Antiguo Vikingo Anciano	Lenguaje Antiguo Vikingo: Es una variedad de lenguaje vikingo denominado lenguaje de ancianos.\n\nSu traduccin al espaol no es exacta sino aproximada, pero puede..
21	tatabra campo	tatabrat@mail.com	2025-05-21 21:00:28.535456-05	$2y$10$C9T85Bw3B5A3tgwWzIS90e14y.uSAiH3kVSgpcGp/Fqhe3paOQxG6
1	Andrs Carvalo	andrescalv01@mail.com	2025-05-04 18:06:01-05	$2y$10$6cdCjPLb6kApN.gKZuTDkOLEGqaf.cVoY.fgO3DD.eEW1AxtbnjMu
17	Jeferson Unigarro	jeferson@mail.com	2025-05-16 18:25:32.578165-05	$2y$10$Y6UecQcbxwgWyagnpXpnuebphmuEgJCMlypNdeAbQhq4glj/2XX.6
18	Cheche	cheche@mail.com	2025-05-16 18:40:44.682924-05	$2y$10$G1OF.7tBrYsnSfZY/JGfRunrcwjeErMw.W6b/x50a.050oC0omK3.
2	Romario De Souza	romariodesouza24@mail.com	2025-05-03 18:06:01-05	$2y$10$iZCtrFpEtqBygWTerQRM8eFEZD/tnmMZLXLBbPRKHFXZ2EwMDzYcO
20	chiguiro	chiguiro@mail.com	2025-05-18 20:51:32.868763-05	$2y$10$KAFLUH7SgZ6vQn/B5sL7nu3Bo1cmFSHHmhq.cC4klHoH.zD94/aX.
15	Vivian Lucero	vivian@mail.com	2025-05-15 12:25:36.840215-05	$2y$10$BrA1OiXrC1KbPUn8LJm07uR/OyGMxCW63mW9r4.oeDu.3x4cumnJm
AC777	Paulo	paulo@mail.com	$2y$10$VRxaOWhFYT7dRYF/cFqYXe7dri0NXOGN79k9aD4BV0CV.301UjQG2	1	1	1
SELECT pg_catalog.setval('public.usr_id_seq', 1, false);
SELECT pg_catalog.setval('public.usr_id_usr_seq', 1, false);
SELECT pg_catalog.setval('translator."Original_Texts_id_seq"', 92, true);
SELECT pg_catalog.setval('translator."Shipping_History_id_seq"', 10, true);
SELECT pg_catalog.setval('translator."Translation_Requests_id_seq"', 99, true);
SELECT pg_catalog.setval('translator."Translations_id_trans_seq"', 30, true);
SELECT pg_catalog.setval('translator."Types_Writing_id_seq"', 2, true);
SELECT pg_catalog.setval('translator."Usr_id_seq"', 26, true);
SELECT pg_catalog.setval('translator.usr_id_seq', 1, false);
SELECT pg_catalog.setval('translator.usr_id_usr_seq', 1, false);
ALTER TABLE ONLY translator."Original_Texts"
    ADD CONSTRAINT "Original_Texts_pkey" PRIMARY KEY (id_orig_t);
ALTER TABLE ONLY translator."Shipping_History"
    ADD CONSTRAINT "Shipping_History_pkey" PRIMARY KEY ("id_shipp_H");
ALTER TABLE ONLY translator."Translation_Requests"
    ADD CONSTRAINT "Translation_Requests_pkey" PRIMARY KEY (id_t_reque);
ALTER TABLE ONLY translator."Translations"
    ADD CONSTRAINT "Translations_pkey" PRIMARY KEY (id_trans);
ALTER TABLE ONLY translator."Types_Writing"
    ADD CONSTRAINT "Types_Writing_pkey" PRIMARY KEY (id_typ_w);
ALTER TABLE ONLY translator.usr_admin
    ADD CONSTRAINT "Usr_Admin_pkey" PRIMARY KEY (id_usr);
ALTER TABLE ONLY translator.usr
    ADD CONSTRAINT "Usr_pkey" PRIMARY KEY (id_usr);
ALTER TABLE ONLY translator."Original_Texts"
    ADD CONSTRAINT "Original_Texts_cod_trad_resq_fkey" FOREIGN KEY (cod_trad_resq) REFERENCES translator."Translation_Requests"(id_t_reque) NOT VALID;
ALTER TABLE ONLY translator."Original_Texts"
    ADD CONSTRAINT "Original_Texts_cod_typ_writing_fkey" FOREIGN KEY (cod_typ_writing) REFERENCES translator."Types_Writing"(id_typ_w) NOT VALID;
ALTER TABLE ONLY translator."Shipping_History"
    ADD CONSTRAINT "Shipping_History_cod_translation_fkey" FOREIGN KEY (cod_translation) REFERENCES translator."Translations"(id_trans) NOT VALID;
ALTER TABLE ONLY translator."Translation_Requests"
    ADD CONSTRAINT "Translation_Requests_cod_usr_fkey" FOREIGN KEY (cod_usr) REFERENCES translator.usr(id_usr) NOT VALID;
ALTER TABLE ONLY translator."Translations"
    ADD CONSTRAINT "Translations_cod_text_oring_fkey" FOREIGN KEY (cod_text_oring) REFERENCES translator."Original_Texts"(id_orig_t) NOT VALID;
ALTER TABLE ONLY translator.usr_admin
    ADD CONSTRAINT "Usr_Admin_cod_transl_fkey" FOREIGN KEY (cod_transl) REFERENCES translator."Translations"(id_trans) NOT VALID;
ALTER TABLE ONLY translator.usr_admin
    ADD CONSTRAINT "Usr_Admin_cod_usr_fkey" FOREIGN KEY (cod_usr) REFERENCES translator.usr(id_usr) NOT VALID;
